/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author CL3-PC38
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("1/x");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 217, 93, 39));

        jButton2.setText("x√²");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 217, 93, 39));

        jButton3.setText("÷");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 217, 93, 39));

        jButton4.setText("x²");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 217, 93, 39));

        jButton5.setText("9");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 262, 93, 39));

        jButton6.setText("x");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 262, 93, 39));

        jButton7.setText("8");
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 262, 93, 39));

        jButton8.setText("7");
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 262, 93, 39));

        jButton9.setText("6");
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 307, 93, 39));

        jButton10.setText("-");
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 307, 93, 39));

        jButton11.setText("5");
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 307, 93, 39));

        jButton12.setText("4");
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 307, 93, 39));

        jButton13.setText("3");
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 352, 93, 39));

        jButton14.setText("+");
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 352, 93, 39));

        jButton15.setText("2");
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 352, 93, 39));

        jButton16.setText("1");
        getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 352, 93, 39));

        jButton17.setText(".");
        getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 397, 93, 39));

        jButton18.setText("=");
        getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 397, 93, 39));

        jButton19.setText("0");
        getContentPane().add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 397, 93, 39));

        jButton20.setText("+/-");
        getContentPane().add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 397, 93, 39));

        jButton25.setText("C");
        getContentPane().add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 172, 93, 39));

        jButton26.setText("←");
        getContentPane().add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 172, 93, 39));

        jButton27.setText("CE");
        getContentPane().add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 172, 93, 39));

        jButton28.setText("%");
        getContentPane().add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 172, 93, 39));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 16, 390, 144));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
